language: scala

# only trigger builds on master
branches:
  only:
    - master
    - v3.1.x

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - export SBT_OPS=-Xmx4G
  - if [[ -n "$CODACY_PROJECT_TOKEN" && $TRAVIS_SCALA_VERSION == 2.12* ]]; then sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate codacyCoverage; else sbt ++$TRAVIS_SCALA_VERSION test; fi

scala:
   - 2.12.12
   - 2.13.6

before_install:
    - pip install --user codecov

after_success:
  - if [[ $TRAVIS_SCALA_VERSION == 2.12* ]]; then codecov; fi

jdk:
  - openjdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bca0308f59d7ad2cb1f
    on_success: always
    on_failure: always
    on_start: never
